### ISSUE TITLE
Can moon make use closure compiler?

### ISSUE THREAD

**Issue by AnthonyJacob** [ethereum/moon-lang#21]
* [Basic requirements](https://developers.google.com/closure/compiler/docs/limitations). 
* [Advanced requirements](https://developers.google.com/closure/compiler/docs/api-tutorial3).

---

* Does moon JIT compiler meet those requirements?
* Is there any chance that compiling moon to javascript, compiling it with closure and running it will outperform the current JIT compiler?

**Comment by VictorTaelin** [comment]
Yes, but Moon is mean to be used as a micro library. Closure is huge and in Java, so it can't be a micro lib on npm. The only way I see Closure being useful is if you compiled a huge library in Moon to JavaScript, and then used Closure to publish a minified JS library to the JS community. In fact, I like the idea, so I've just set up a repository to explain how that could work:

https://github.com/MaiaVictor/moon-bignum

Note that, with the `#` operator, and since Moon is pure, you can perform any amount of compile-time computations as you want, going much further than what closure-compiler. Of course, you need to do it yourself, but the performance gains can be astonishing when you inline the right things.
