### ISSUE TITLE
Understanding Lexer.

### ISSUE THREAD

**Issue by Kesanov** [ethereum/moon-lang#23]
I read trough the `moon-syntax.js`, because I wanted to try out few ideas, but it is not exactly easy to understand (no type signatures, giant functions, no comments). The biggest obstacle so far for me were the function `lifted` and arguments of `parse(vs, li, isKey, isPri)`. 

What does function `lifted` do and what is the purpose of `vs` and `li`? 

Also, what are the types of `E` `T` and `S` ?

Thanks!

**Comment by MaiaVictor** [comment]
Oh. So, the main point of Moon is that we agree with a simple, common core [this file](https://github.com/MaiaVictor/moon-lang/blob/master/src/moon-specs.js) and a binary format [this one](https://github.com/MaiaVictor/moon-lang/blob/master/src/moon-pack.js). The new Mist browser (still to be released), for example, loads the binary format from IPFS, not the plain-text syntax. You, thus, do not need to use the current syntax, and *much less* understand its implementation! As such, it is probably the least comprehensible part of this repository.

If you still want to understand it because of reasons, here are those types and some comments:

```haskell
-- This specifies if this term is expanded at compile time.
-- This affects parsing of variables bound by a `let`. If a
-- term is expanded at compile time, a variable bound by
-- a `let` will be inlined in-place. It is true when we're
-- inside a `#`.
E : Bool

-- T is how terms are stored, church-encoded, with
-- a JavaScript object specifying the constructors.
T : Term
type Term = ∀ r . {
  App: r -> r -> r,
  Lam: String -> r -> r,
  Var: String -> r,
  Ref: String -> r,
  Let: String -> r -> r -> r,
  Fix: String -> r -> r,
  Pri: String -> [r] -> r,
  Num: Number -> r,
  Str: String -> r,
  Map: [(String,r)] -> r,
  Nor: Term
} -> r

-- Through the parser, I represent linked lists as either an 
-- JS array with a value and the tail, or null, representing []
type List a = [a, List] | null

-- `vs` is a list of tuples containing bound var names. It can
-- also associate those names with either:
-- 1. The string "_rec", indicating it the name used by a let on
--   its own definition. This is not currently allowed because of 
--   the way tail-recursive functions work (but should be). So, if
--   you write `x = (... x ...) something`, it throws.
-- 2. A term, if it was bound by a let. This is used to expand it
--   statically when `E` is true (i.e., we're inside a `#`).
vs : List (String, Either "_rec" (Maybe Term))

-- Stands for `scope`, is a list of bound variables. It is used
-- on `finalize` to replace unbound variables by a special
-- constructor. `finalize` also performs compile-time expansions
-- of terms prefixed with `#` (the `Nor` constructor).
S : List String

-- This is a list of terms found prefixed with a `<` inside a bang-notation
-- context. Example: `| ... <(add 1 1) ...` would append `["_0", (add 1 1)]`
-- to `li`. This allows us to capture banged expressions as we parse
-- the term. When it finds a `|` (or a let/lam/fix, because there is an
-- implicit `|` after any bounding expression), we know where to insert
-- those captured terms, using `lifted()`. This is the generic mechanism
-- to flatten callbacks, avoiding callback hell in monadic computations.
li : List (String, Term)
```

Note that this parser is quite nice because it is fast, direct and small, but understanding it will be very difficult. If I don't completely replace it soon enough, eventually I'll add comments and improve its style.

**Comment by VictorTaelin** [comment]
Oh. So, the main point of Moon is that we agree in a simple, common core ([this file](https://github.com/MaiaVictor/moon-lang/blob/master/src/moon-specs.js)) and a binary format ([this one](https://github.com/MaiaVictor/moon-lang/blob/master/src/moon-pack.js)). The new Mist browser, for example, will load the binary format from IPFS, not the plain-text syntax. You do not need to use the current syntax, and *much less* understand its implementation! As such, it is probably the least comprehensible part of this repository.

If you still want to understand it because of reasons, here are those types and some comments:

```haskell
-- This specifies if this term is expanded at compile time.
-- This affects parsing of variables bound by a `let`. If a
-- term is expanded at compile time, a variable bound by
-- a `let` will be inlined in-place. It is true when we're
-- inside a `#`.
E : Bool

-- T is how terms are stored, church-encoded, with
-- a JavaScript object specifying the constructors.
T : Term
type Term = ∀ r . {
  App: r -> r -> r,
  Lam: String -> r -> r,
  Var: String -> r,
  Ref: String -> r,
  Let: String -> r -> r -> r,
  Fix: String -> r -> r,
  Pri: String -> [r] -> r,
  Num: Number -> r,
  Str: String -> r,
  Map: [(String,r)] -> r,
  Nor: Term
} -> r

-- Through the parser, I represent linked lists as either an 
-- JS array with a value and the tail, or null, representing []
type List a = [a, List] | null

-- `vs` is a list of tuples containing bound var names. It can
-- also associate those names with either:
-- 1. The string "_rec", indicating it the name used by a let on
--   its own definition. This is not currently allowed because of 
--   the way tail-recursive functions work (but should be). So, if
--   you write `x = (... x ...) something`, it throws.
-- 2. A term, if it was bound by a let. This is used to expand it
--   statically when `E` is true (i.e., we're inside a `#`).
vs : List (String, Either "_rec" (Maybe Term))

-- Stands for `scope`, is a list of bound variables. It is used
-- on `finalize` to replace unbound variables by a special
-- constructor. `finalize` also performs compile-time expansions
-- of terms prefixed with `#` (the `Nor` constructor).
S : List String

-- This is a list of terms found prefixed with a `<` inside a bang-notation
-- context. Example: `| ... <(add 1 1) ...` would append `["_0", (add 1 1)]`
-- to `li`. This allows us to capture banged expressions as we parse
-- the term. When it finds a `|` (or a let/lam/fix, because there is an
-- implicit `|` after any bounding expression), we know where to insert
-- those captured terms, using `lifted()`. This is the generic mechanism
-- to flatten callbacks, avoiding callback hell in monadic computations.
li : List (String, Term)
```

Note that this parser is quite nice because it is fast, direct and small, but understanding it will be very difficult. If I don't completely replace it soon enough, eventually I'll add comments and improve its style.

**Comment by Josef-Vonasek** [comment]
I think the `var index` is doing more harm than good. 

* It makes parsing sequential for no apparent reason. Take the following example

```haskell
a = complicatedTerm
b = complicatedTerm
c = complicatedTerm
d = foo a b c
```
It is obviously possible to build AST for `b` and `c` and `d` without knowing `a`.

* It makes the code harder to reason about.

I am not sure how much would calling `source.slice` damage the performance, but in theory it should not make a difference.

**Comment by Kesanov** [comment]
Reading trough the code `{a:1 b:3]` should return map `{a:1 b:3}` because your test for map end looks like `if (/(\}|\]|\))/.test(source[index])`. Yet `moon run "{a:1]"` returns an error. 

Are you using newer version of moon-syntax in moon-tool?

**Comment by VictorTaelin** [comment]
```
moon run "{a:1]"
```

Returned an error because when the parser found the last `]`, it was expecting either a key (because `isKey == true`) or a `}`. Since `]` isn't `}`, then it must be a key. It attempted to parse `]` as a key and failed. That was indeed a bug.

**Comment by Kesanov** [comment]
> it was expecting either a key (because isKey == true) or a }

The problem is I could not find any function that tests for `}` and only `}`. I found `(/(\}|\]|\))/.test(source[index])` which does not make a difference between `}`, `]` and `)`. That's why I am confused.

**Comment by VictorTaelin** [comment]
You missed line 79, then (check the commit above)!

**Comment by Kesanov** [comment]
Have you thought about adding `let .. in ..` (alternatively `( .. let goes here .. ) ..` )? The code then requires much less parentheses.
