### ISSUE TITLE
Incomplete interop with JavaScript

### ISSUE THREAD

**Issue by Pyrolistical** [ethereum/moon-lang#8]
You have implemented a runtime in JavaScript and moon-lang is meant to be called from JavaScript, yet there lacks faculties to return null, booleans, or arrays from moon-lang.

Is your goal to be useful from JavaScript, or are you just using JavaScript because its everywhere?

If you intend to have different non-JavaScript runtimes, then what you have today is fine.

However, my goals with [deft](https://github.com/concept-not-found/deft) is to interop fully with JavaScript, which means we might not be able to share runtimes/syntaxes

**Comment by MaiaVictor** [comment]
The primitives were not added for JS interop! They were added because they're required for performance: there is, so far, no obvious way to get floating point arithmetic, strings and hash tables as efficient as their λ-encoded counterparts. As such, `Map`, `Str` and `Num` is the minimal set of things that made the λ-calculus practical.

Note that JS interop does not require those! You could perfectly well translate JS data to λ-encoded data, and back. Of course, given that Str and Num behave exactly like JS numbers, you **can** use those, but this is to be considered a bonus / coincidence. Similarly, Map behave exactly like JS objects, so you can use them. For arrays, you can simply translate any Map with a `.length` field and numeric indices to a JS array. If you don't want to do that, you can instead compile maps and arrays to a tagged union (i.e., a scott-encoded Either), so you know which is which. But again: the primitives are not here for JS interop, they're here because the λ-calculus needs them to be fast.

As soon as I find a way to remove those primitives, they will. It is very likely that I can convert pure λ-encodings to native Strings, Maps and Array when executing the code. If so, I'll remove all of those. Moon 2.0 will likely be just Morte (ironically killing it).

**Comment by VictorTaelin** [comment]
The primitives were not added for JS interop! They were added because they're required for performance: there is, so far, no obvious way to get floating point arithmetic, strings and hash tables to run with λ-encoding as efficiently as the native representations. As such, `Map`, `Str` and `Num` are the minimal set of additions to make the λ-calculus practical. Note that JIT engines compile arrayish-map usage to actual arrays, so arrays are not needed for performance!

Host-language interop is a different concern, and it does not require those primitives! It just requires a consistent way to translate from native terms to Moon-terms, and back. The untyped λ-calculus with λ-encodings (i.e., no primitives) is already sufficient to any kind of interop. Now, of course, given that Str, Num and Map behave exactly like JS numbers, strings and objects, you should use those for performance. For arrays, I simply interpret any Moon Map with a `.length` field and numeric indices as a JS array. Of course, that means there is no way to encode an actual map with a `.length` field and numeric indices. If you don't want that ambiguity, you can just use a scott-encoded sum type on Moon's side (i.e., Either Array Map).

Note, again, primitives have nothing to do with interoperability, they're a short-term pollution that is there only for practicality. As soon as I find a way to get rid of them (i.e., a satisfactory way to compile λ-encodings to native Strings, Maps and Array), I will. Moon 2.0 will likely be just Morte (ironically killing it).

**Comment by Pyrolistical** [comment]
ok cool, I think this is where we'll have to part ways then. my ast will mirror the capabilities of javascript 1:1 in order to have simple interop.  I could have full interop with moon-lang if i keep additional data while translating from deft -> moon -> javascript, but honestly that seems like a waste of time and will bloat the binary encoding.

thank you for inspiring me and i'll definitely keep an eye on this project

**Comment by MaiaVictor** [comment]
No problems, thank you!

**Comment by VictorTaelin** [comment]
Ah, that's sad. Wish you all the best and I hope you come back!

> thank you for inspiring me and i'll definitely keep an eye on this project

No problems, and thank you actually!
