### ISSUE TITLE
The quest for readable core: Syntactic sugar.

### ISSUE THREAD

**Issue by AnthonyJacob** [ethereum/moon-lang#9]
Do we want *any* syntactic sugar in moon? 

-----
E.G. shorter syntax for functions 
`foo one two three : ...` = `foo : one. two. three. ...`

**Comment by VictorTaelin** [comment]
That function can be written as `(add 1)`.

**Comment by AnthonyJacob** [comment]
@MaiaVictor of course, but sometimes currying is not an option.

Anyway that example was just an example of what I mean by syntactic sugar. The first sentence is the important one.

**Comment by VictorTaelin** [comment]
I don't get what this issue is about! You're asking if we should have this specific syntax sugar? Moon has a bunch of syntax sugars already, I'm all for them (as long as they don't affect the core). It would have more if I had the time - it is all about making a good parser and stringifier. 

BTW in a few moments I'm going to update the default syntax to use `=` for `let` and `=>` for lambdas (you guys won, I guess!)

**Comment by AnthonyJacob** [comment]
Fine, I just was not exactly sure, whether you want to add more.

To be honest, I would rather keep the `.` syntax for lambdas - it is much more concise. On the other hand I am afraid javascripters would be really confused.

**Comment by VictorTaelin** [comment]
Yep, I had a friend specifically struggle for hours understanding a λ-term. Then I replaced `.`s by arrows and he said: *"oh, that's much better, I get it now"*! I think those things might matter more than I'd think. Also, the arrow syntax plays well with types as we can have `->` for `forall` and `=>` for lambdas, which everyone immediately recognizes.

At least `=` is clearly better than `:` for lets, I guess.
